#!/bin/bash

CONF_PATH="$HOME/config"

if [ ! -z $1 ]; then
    sudo cat "$CONF_PATH/private_ssh.txt" | sudo tee "$HOME/.ssh/config" && \
    echo -e "\n개인용 SSH 설정"
    exit 0
else
    sudo cat "$CONF_PATH/company_ssh.txt" | sudo tee "$HOME/.ssh/config" && \
    echo -e "\n업무용 SSH 설정"
fi
